### ISSUE TITLE
[Bug]: Checkout Process - User field is missing

### ISSUE THREAD

**Issue by hjakovski** [snipe/snipe-it#18053]
### Snipe-IT Version

v8.3.3 Build 20061 (master)

### PHP Version

8.2.29

### Composer Version

2.8.11

### MySQL/MariaDB version

MySQL 10.11.14

### How did you install Snipe-IT?

Git install

### Is this a fresh install or an upgrade?

Upgrade

### What happened?

When you try to checkout something the search field for the USER is missing. It shows up when you click the Asset Tab and back to User. Reproducable on the demo system.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Can you reproduce this on the public demo?

Yes

### Do you have full multiple company support enabled?

No

### If you have full multiple company support enabled, do you have location scoping to company enabled?

I do not have full multiple company support enabled

### Application log output

```shell

```

### Browser console output

```shell

```

### Common Issues

- [x] I have searched this repo for existing issues related to my issue (including closed issues)
- [x] My APP_URL is set correctly in my .env file (including http or https and no trailing slash)
- [x] I have searched the official Snipe-IT documentation and have checked the Common Issues documentation (where applicable)
- [x] I have run database migrations (where applicable).
- [ ] I have attached screenshots and/or videos of the issue (where applicable)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by snipe** [comment]
This was fixed 3 weeks ago and is on master. An upgrade should fix you. https://github.com/grokability/snipe-it/pull/17923

**Comment by hjakovski** [comment]
Updated today to 8.3.3 so why is it not working ? Did i miss something ?
Cleared cache and config cache stuff, too.

Can still reproduce it on the demo system, too.

The #17923 looked fo me as it was only included into:  grokability:develop

**Comment by snipe** [comment]
> The https://github.com/grokability/snipe-it/pull/17923 looked fo me as it was only included into: grokability:develop

Develop was merged into master several times so that fix would have been on master already.

**Comment by hjakovski** [comment]
The field for the username search is missing in the demo, too.

<img width="1415" height="892" alt="Image" src="https://github.com/user-attachments/assets/7e4059bc-1b5a-420d-b7bb-407740220468" />

**Comment by hjakovski** [comment]
Seems like the latest Update Build 20183 fixed it for the Assets. But in Accessoires & License the field is still missing.
Thanx.

**Comment by hjakovski** [comment]
Fixed in the latest relöease. Thanx. ;-)
