### ISSUE TITLE
Preflight .env check false error

### ISSUE THREAD

**Issue by TeejMonster** [snipe/snipe-it#3583]
I get an invalid setting notification on the Pre-flight checklist:

```Config File X  Please make sure your .env. You don't ever want anyone able to see that file. Ever. Ever ever. Click here to check now (This should return a file not found or forbidden error.)```

When I click the link to check, I get a 404 as expected (with http code 200).  Looks like an issue with the logic to check for that file.  On line 67 of SettingsController.php, the checklist is just seeing if anything gets returned and is getting back the code for the 404 page, which sets the flag to true.

```php
$exposed_env = @file_get_contents($protocol . $host.'/.env');

if ($exposed_env) {
    $start_settings['env_exposed'] = true;
} else {
    $start_settings['env_exposed'] = false;
}
```

Also, there seems to be an incomplete sentence in the warning.  Looks like it should be something like:
```php
Please make sure your <code>.env</code> isn't exposed to the internet. You don't ever want anyone able to see that file. Ever. Ever ever.  <a href="../../.env">Click here to check now</a> (This should return a file not found or forbidden error.)
```

- [ x ] I have enabled debug mode
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Snipe-IT version: 4.0alpha2
OS: Ubuntu 16.04
Server: Apache2 with PHP7
Install method: manual
URL: /setup

**Comment by ianabc** [comment]
I'm seeing the same behaviour, checking the URL gives a 404 but the preflight marks it up as a problem.

Snipe-IT version: 3.6.5
OS: CentOS 7
Sever: Apache/2.4.6 with PHP/5.6.30
Install method: manual

**Comment by TeejMonster** [comment]
Possible solution is to have preflight check to see if file really is env or if the returned code is 404 html.

**Comment by ianabc** [comment]
If it turns out that this is a bug, I thought of just trying to get the HTTP response code, e.g.

```php
$ch = curl_init($protocol . $host.'/.env');
curl_setopt($ch, CURLOPT_HEADER, true);    // we want headers
curl_setopt($ch, CURLOPT_NOBODY, true);    // we don't need body
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_TIMEOUT, 10);
$output = curl_exec($ch);
$httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

if($httpcode == 404 || $httpcode == 403) {
    $start_settings['env_exposed'] = false;
} else {
    $start_settings['env_exposed'] = true;
}
```

**Comment by TeejMonster** [comment]
When I tried that I got a 200 back.

**Comment by ianabc** [comment]
Yeah, I just checked and I see that as well, the 404 page is sending back the wrong response code.

**Comment by TeejMonster** [comment]
The default error handler in this version of Laravel doesn't specify an HTTP status for error pages.  For 404 pages specifically, the following change can cause a 404 status to be returned rather than a 200.

In __app\Exceptions\Handler.php__ on lines 58-61, change:

```php
case '404':
  return response()->view('layouts/basic', [
      'content' => view('errors/404')
  ]);
```

to:

```php
case '404':
  return response()->view('layouts/basic', [
      'content' => view('errors/404')
  ],404);
```

I found that solution in this [Stack Overflow post](https://stackoverflow.com/questions/42614264/how-to-make-laravel-5-return-404-status-code) which matches up with [Laravel Documentation](https://laravel.com/docs/5.3/responses) regarding HTTP response codes.  Between that and the CURL check you mentioned, I think that should fix the pre-check issue.

I'm new to this, but do we submit a pull request once the fix is fully fleshed out?

**Comment by ianabc** [comment]
I think so, I would just submit what you have now as a pull request and let the maintainers review the changes etc. Good work, thanks!

**Comment by snipe** [comment]
This is fixed in develop and will be in the v4 release - thanks!

**Comment by OprSysAdm** [comment]
Good Afternoon,

I have just installed v4.1.3 and still getting this false positive in my config file section with red x despite what appears to a properly functioning setup. Just thought you should know.

**Comment by tx7** [comment]
This error still exist in v4.1.14

**Comment by aviemet** [comment]
Error still exists in v4.6.2

**Comment by stratos528** [comment]
I just ran into the same issue.  I configured AWS to only allow 1 IP address to access the server and the config file check would always fail.  When I allowed http and https connections from the servers elastic IP address/public IP address, the check went green.  A good check to see if it is networking related would be to see if you can get to your server using "lynx Your-Snipe-IT-URL-Here" from your snipe-it server.  You could probably just use a browser if you are using windows with a GUI.  If you can't access your server using its URL, the check will fail since it is not getting the expected failure message.

**Comment by Deitsch** [comment]
Error still exists on v4.7.4
