### ISSUE TITLE
Import hangs

### ISSUE THREAD

**Issue by tosterbe** [snipe/snipe-it#3980]
#### Expected Behavior (or desired behavior if a feature request)

Importing 6 rows of data (1 header, 5 assets) to be successful.  Import is from a test file

-----

#### Actual Behavior
I am able to map fields in the UI between the DB and CSV file.  
Clicking on import button, app hangs once it displays a green 'processing...'  notification.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
>>> v4 beta 5
- What OS and web server you're running Snipe-IT on 
>>> Debian 9, apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
>>> 
[import-va442.txt](https://github.com/snipe/snipe-it/files/1316528/import-va442.txt)

manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
>>> no error displayed
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Any errors that appear in your browser's error console.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
(Also try upgrading to beta 6 - I believe we fixed some importer issues in that release)

**Comment by dmeltzer** [comment]
javascript console errors/web console network tab errors would be interesting to see in these instances.

**Comment by tosterbe** [comment]
Sorry, was unable to provide info before now.  I've upgraded to 4.0.4 and still have the problem.

Javascript console shows:

Failed to load resource: the server responded with a status of 500 (Internal Server Error). << blank space >> https://inventory/api/v1/imports/process/2

Network shows a series of status 200 then one status 500 for the POST method.

**Comment by snipe** [comment]
@tosterbe need the app error so we can see what the 500 error is, as was requested in the initial issue template.

**Comment by tosterbe** [comment]
Last 'interesting' line from apache2 error log:

[Wed Sep 27 18:53:53.587860 2017] [:error] [pid 825] [client 16.214.97.141:49756] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/snipeit/storage/logs/laravel
.log" could not be opened: failed to open stream: **Permission denied** in /var/www/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:
#0 /var/www/snipeit/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)
#1 /var/www/snipeit/vendor/monolog/monolog/src/Monolog/Logger.php(337):
 Monolog\\Handler\\AbstractProcessingHandler->handle(Array)
#2 /var/www/snipeit/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\
Debug\\Exception\\FatalErrorException), Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Except
ion\\FatalErrorException), Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog('error', Object(Symfony\\Component\\De in
/var/www/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

**file perms**

labuser@snipeit:/var/log/apache2# ls -la /var/www/snipeit/storage/logs/laravel.log
-rwxr-xr-x 1 www-data www-data 164223 Sep 27 20:12 /var/www/snipeit/storage/logs/laravel.log


I don't see any corresponding info matching the date/time stamp above in /var/www/snipeit/storage/logs/laravel.log

**Comment by snipe** [comment]
Well that definitely still looks like a permissions issue. Do you have SELinux enabled by any chance?

**Comment by tosterbe** [comment]
Nope, just double checked.  No SELinux configured.
