### ISSUE TITLE
File Import Issue on v.4.0.4 Stable after migrating from v3.6.6

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#4052]
On Imports Screen Following Issue Appear
Something went wrong fetching files...

Why it Happened:
Upgraded from v3.6.6 to v4.0.4

What I Have Done:
Checked permissions for private_uploads\imports\assets

Error Log:
Invalid Exception: with Message 'Route [View/Hardware] not defined.

![error](https://user-images.githubusercontent.com/1447175/30963007-0318b210-a45d-11e7-85b3-2c49e7af41b5.png)

**Comment by dmeltzer** [comment]
Are you installed in a subdirectory by any chance?  

The error you show is unrelated, though still a bug.

**Comment by raakhtar** [comment]
Well its not in subdirectory . Its under www>snipe-it.

**Comment by snipe** [comment]
This is fixed now, right? From that old route PR?

**Comment by raakhtar** [comment]
not fixed. The message is not shown but following appears.
<img width="1298" alt="screen shot 2017-09-30 at 1 35 58 am" src="https://user-images.githubusercontent.com/1447175/31037014-dcd95ce8-a57f-11e7-8ff4-784986a1de1c.png">

**Comment by snipe** [comment]
We need log output. Browser error log and app log.

**Comment by raakhtar** [comment]
Javascript error: InvalidArgumentException with Message 'Route [View/Hardware] not defined.

**Comment by raakhtar** [comment]
Could you specify from where i should give you the logs ... Location pls

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help#section-step-3-check-your-app-and-server-logs

That route doesn't exist in the code anymore. Try clearing your caches, views etc.

```
php artisan cache:clear
php artisan config:clear
php artisan route:clear
```

**Comment by raakhtar** [comment]
[2017-09-28 14:07:15] production.ERROR: exception 'InvalidArgumentException' with message 'Route [view/hardware] not defined.' in C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php:304
Stack trace:
#0 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(741): Illuminate\Routing\UrlGenerator->route('view/hardware', '132', true)
#1 C:\wamp64\www\snipe-it\app\Http\Controllers\AssetsController.php(383): route('view/hardware', '132')
#2 [internal function]: App\Http\Controllers\AssetsController->update(Object(App\Http\Requests\AssetRequest), '132')
#3 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#4 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('update', Array)
#5 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\AssetsController), 'update')
#6 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#7 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(559): Illuminate\Routing\Route->run()
#8 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 C:\wamp64\www\snipe-it\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\wamp64\www\snipe-it\app\Http\Middleware\CheckForTwoFactor.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 C:\wamp64\www\snipe-it\app\Http\Middleware\CheckLocale.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#33 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#34 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#35 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#36 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\wamp64\www\snipe-it\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\wamp64\www\snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 C:\wamp64\www\snipe-it\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 C:\wamp64\www\snipe-it\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 C:\wamp64\www\snipe-it\app\Http\Middleware\XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 C:\wamp64\www\snipe-it\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 C:\wamp64\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#69 C:\wamp64\www\snipe-it\public\index.php(59): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

**Comment by raakhtar** [comment]
Chrome Log 
<img width="774" alt="screen shot 2017-09-30 at 2 13 06 am" src="https://user-images.githubusercontent.com/1447175/31038000-41ad4026-a585-11e7-9f93-68d8bb45662b.png">

**Comment by dmeltzer** [comment]
What is your app_url? The line ':81/api/v1/imports' 404ing makes me wonder if something is weird there.

**Comment by raakhtar** [comment]
I doubt if thats the issue. anyhow.

APP_URL='http://10.100.20.66:81/snipe-it'

**Comment by dmeltzer** [comment]
Okay, so this is a subdirectory.  That is the issue.  I'll look deeper into a fix.

**Comment by raakhtar** [comment]
but i thought you already fixed the subdirectory issue in 4.0.5 ? isn't

**Comment by snipe** [comment]
Clearly we thought we did too.

**Comment by raakhtar** [comment]
so what is the action on my part @snipe @dmeltzer ?

**Comment by raakhtar** [comment]
OK here is what i did, 
1. Git pull
2. Updated Laravel by running the upgrade instructions
3. Import screen now do not display anything

Errors Shown in JS Console:
1. [Vue warn]: It seems you are using the standalone build of Vue.js in an environment with Content Security Policy that prohibits unsafe-eval. The template compiler cannot work in this environment. Consider relaxing the policy to allow unsafe-eval or pre-compiling your templates into render functions.
warn @ all.js:30795
2. [Vue warn]: Error compiling template:

<div id="app">
    <importer inline-template="" import-url="http://10.100.20.66:81/snipe-it/api/v1/imports" v-cloak="">
        <div class="row">
        <alert v-show="alert.visible" :alert-type="alert.type" v-on:hide="alert.visible = false">{{ alert.message }}</alert>
            <errors :errors="importErrors"></errors>
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-3">
                                
                                <span class="btn btn-info fileinput-button">
                                    <span>Select Import File...</span>
                                    
                                    <input id="fileupload" type="file" name="files[]" data-url="/api/v1/imports" accept="text/csv">
                                </span>
                            </div>
                            <div class="col-md-9" v-show="progress.visible" style="padding-bottom:20px">
                                <div class="col-md-11">
                                    <div class="progress progress-striped-active" style="margin-top: 8px">
                                        <div class="progress-bar" :class="progress.currentClass" role="progressbar" :style="progressWidth">
                                            <span>{{ progress.statusText }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12" style="padding-top: 30px;">
                                <table class="table table-striped" id="upload-table">
                                    <thead>
                                        <tr><th>File</th>
                                        <th>Created</th>
                                        <th>Size</th>
                                        <th></th>
                                    </tr></thead>
                                    <tbody>
                                    	<template v-for="currentFile in files">
                                    		<tr>
                                    			<td>{{ currentFile.file_path }}</td>
                                    			<td>{{ currentFile.created_at }} </td>
                                    			<td>{{ currentFile.filesize }}</td>
                                    			<td>
                                    			<button class="btn btn-sm btn-info" @click="toggleEvent(currentFile.id)">Process</button>
                                    				<button class="btn btn-danger" @click="deleteFile(currentFile)"><i class="fa fa-trash icon-white"></i></button>
                                    			</td>
                                    		</tr>
                                    			<import-file :key="currentFile.id" :file="currentFile" customfieldurl="http://10.100.20.66:81/snipe-it/api/v1/fields" @alert="updateAlert(alert)">
                                    			</import-file>
                                    	</template>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </importer>
</div>

- invalid expression: v-show="alert.visible"
- invalid expression: :alert-type="alert.type"
- invalid expression: v-on:hide="alert.visible = false"
- invalid expression: {{ alert.message }}
- invalid expression: :errors="importErrors"
- invalid expression: v-show="progress.visible"
- invalid expression: :class="progress.currentClass"
- invalid expression: :style="progressWidth"
- invalid expression: {{ progress.statusText }}
- invalid expression: v-for="currentFile in files"
- invalid expression: {{ currentFile.file_path }}
- invalid expression: {{ currentFile.created_at }}
- invalid expression: {{ currentFile.filesize }}
- invalid expression: @click="toggleEvent(currentFile.id)"
- invalid expression: @click="deleteFile(currentFile)"
- invalid expression: :key="currentFile.id"
- invalid expression: :file="currentFile"
- invalid expression: @alert="updateAlert(alert)"


(found in <Root>)
3.Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
all.js:38320 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
4. all.js:61389 Loading up Modal functionality.
(anonymous) @ all.js:61389

**Comment by dmeltzer** [comment]
This is now reached the same underlying issue as #4077.  We're working on a fix.

**Comment by raakhtar** [comment]
3 Major issues in v4.0.6

1. Licence Check in having issue
2. Asset Import having issue
3. When checkin assets by going to Users->Name->Assets->Checkin results in not found redirect.

**Comment by raakhtar** [comment]
any update for this one ?

**Comment by raakhtar** [comment]
Even after pulling from the latest 4.0.8 build 1.0.2, the import issue persists. Kindly note that Snipe-IT is running in a subdirectory.

Javascript Console Issues:

![image](https://user-images.githubusercontent.com/1447175/31128902-1eaf80fc-a864-11e7-8563-c78de6c89fa5.png)

**Comment by raakhtar** [comment]
i believe @dmeltzer this is still in development and has not been merged in production for me to give it a try if this fixed it.

**Comment by raakhtar** [comment]
any update on this ? @snipe @dmeltzer

**Comment by dmeltzer** [comment]
Have you tried 4.0.9?

**Comment by raakhtar** [comment]
Yes the issue persists in 4.0.9 too

**Comment by dmeltzer** [comment]
And it's the same error message you posted before?  And your APP_URL is set correctly?

**Comment by raakhtar** [comment]
Yes it is ...kindly note that this was working on v3.6.6 and it stopped working when migrated to 4.0.6

Have even tried fresh install of 4.0.9.

Please configure subdirectory to see the errors for yourself

**Comment by tbradsha** [comment]
I can confirm this is also occurring for me in a v4.0.9 build 120 subdirectory install. Not sure if this helps, but I notice at least one reference to an absolute URL on the import page (changing it prior to import doesn't help, though):

<input data-v-5301a236="" id="fileupload" type="file" name="files[]" data-url="/api/v1/imports" accept="text/csv">

**Comment by raakhtar** [comment]
Fixed in v4.0.10
