### ISSUE TITLE
Status label 'Deployed'

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#4099]
#### Expected Behavior (or desired behavior if a feature request)

According to the left nav bar deployed assets should have a blue circle as status icon.

-----

#### Actual Behavior

The status icon is red cross representing 'Undeployable/Archived'.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Is this a fresh install or an upgrade? Upgrade
Version of Snipe-IT you're running:  v4.0.9 build 120 (gf66e222)
Version of PHP you're running: 5.6.29
Version of MySQL/MariaDB you're running: MariaDB 10.1.3
What OS and web server you're running Snipe-IT on: win7x64, nginx
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Can I have some screenshots here? I don't really have any way of knowing what you're referring to.

**Comment by diekmanu** [comment]
Click on the 'Deployed' / "All Herausgegeben" view:
![2017-10-04_08h27_08](https://user-images.githubusercontent.com/13235891/31162471-eeb46654-a8dd-11e7-8c1b-a544ea48d6a7.png)

Status label icons don't match:
![2017-10-04_08h21_33](https://user-images.githubusercontent.com/13235891/31162496-1d3fd224-a8de-11e7-91eb-35aee7b05322.png)

**Comment by diekmanu** [comment]
I guess it's some kind of statuslabel ID mismatch. On the demo pages (where icons match) the deployed statuslabel ID is '8'. In my enviroment '8' is a custom status linked to undeployable.

**Comment by diekmanu** [comment]
Okay...the problem seems to be related with the language files:

German:
![2017-10-11_11h41_58](https://user-images.githubusercontent.com/13235891/31433573-10490940-ae7a-11e7-9957-7b57e69002ee.png)

So when I change

`'deployed'				=> 'Herausgegeben',`
back to
`'deployed'				=> 'deployed',`

in **resources\lang\de\general.php**

Voilà...the blue circle is back again.

US:
![2017-10-11_11h42_50](https://user-images.githubusercontent.com/13235891/31433594-1f253b50-ae7a-11e7-9680-9c23e37e4e0f.png)

@snipe Any way to get it working without reverting back to US-English?

Thanks!

**Comment by diekmanu** [comment]
This is still a problem in v4.1.3 build 94 (gb6a14d2)

**Comment by CronKz** [comment]
Still a problem in 4.1.6

**Comment by snipe** [comment]
I believe this has been fixed.
<img width="1433" alt="screen shot 2017-12-12 at 6 13 05 am" src="https://user-images.githubusercontent.com/197404/33888980-90860ebe-df03-11e7-995c-e67908e6f3c4.png">

**Comment by CronKz** [comment]
This is still not fixed.
I am running now (Version v4.1.9-pre - build 3117 (master)).
And like I have mentioned in #4535 

> This only happens when "APP_LOCALE" in .env is set to "de"!

**Comment by diekmanu** [comment]
Yep, same issue here.

**Comment by snipe** [comment]
Can anyone confirm if this is still happening? I cannot reproduce it locally. I've tried changing the `APP_LOCAL` to `de` in the `.env` file (and in the system locale, and my user preferences), but can't get it to happen here.

**Comment by ovizii** [comment]
Seeing something similar on v4.6.3 - build 3866 (master) see my thread: https://github.com/snipe/snipe-it/issues/6117#issuecomment-415687413

![image](https://user-images.githubusercontent.com/837902/44575351-14248d80-a78c-11e8-987b-8e150a143d5d.png)
