### ISSUE TITLE
Serial Number not importing

### ISSUE THREAD

**Issue by getschools** [snipe/snipe-it#5108]
#### Expected Behavior (or desired behavior if a feature request)

.csv import with "Serial Number" as a field heading will import the asset's serial number

-----

#### Actual Behavior

Asset is imported, but no serial number is associated. If the .csv heading is changed to simply "Serial" the serial number is imported.

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Pretty Fresh**
- Version of Snipe-IT you're running **Version v4.1.14 - build 3391 (master)**
- Version of PHP you're running **PHP 7.0.27-0+deb9u1**
- Version of MySQL/MariaDB you're running **mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2**
- What OS and web server you're running Snipe-IT on **Debian 9, NGINX**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Git**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
@dmeltzer can you take a look when you get a chance?

**Comment by Crimsonfox89** [comment]
Just encountered this today when using the CLI importer. Recognises the "Serial" column in a csv but not "Serial Number".

Running v4.4.1 - build 3636 (master) on Win Server 2012 R2, IIS.

**Comment by jaymaan07** [comment]
Similar issue 

Running Version v4.6.3 - build 3866 (master) on Win Server 2016

**Comment by Speed1** [comment]
Still an issue

**Comment by ColinMcNeil** [comment]
Hey I just wanted to mention I just had this issue as well. The example csv on the docs has it as `Serial number` which doesn't work. Knowing this would have saved me 45 minutes of debugging and googling.

**Comment by slyr91** [comment]
Glad this issue existed and had a solution. I just imported over a thousand assets and noticed all the missing serial numbers. Gave me anxiety thinking I might have to update each one manually lol. I would think this is an easy fix. Probably not being seen because of it being closed by the stale bot?

**Comment by Bakan0** [comment]
un-stale?

**Comment by Brassn** [comment]
For me it is now the other way arround. If I use "Serial" as (now) stated in the documentation (https://snipe-it.readme.io/docs/importing) it doesn't populate the field during import.
If I use "Serial Number" as column name it works as intended and automatically assignes the field in the import mask.

So it seems like this issue was fixed in code but the documentation was also changed to respect the old behavior so it is now exactly the other way around.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>

**Comment by NakedHammer** [comment]
Using the Web GUI importer I associated my csv Column "Serial" to the target "Serial Number" and the import worked but no serial numbers were imported. Changing the the csv column header to "Serial Number" worked. Note: The importer auto mapper recognised it and pre selected "Serial Number" as the target field as well once changed.

**Comment by sdk1-kod** [comment]
Can, we reopen this ticket, I can recreate.

- If the header field is set to 'Serial' on the imported .csv file, no 'Serial' fields are imported.
- If the header field is set to 'Serial Number' on the imported .csv file, 'Serial Number' fields ARE imported.

Please note
<blockquote class="prompt-warning"><div><p>When doing 'Custom Export' the .csv file has 'Serial' as the header.</p></div></blockquote>

**Comment by marcusmoore** [comment]
This should be solved with #12249 that got merged to the develop branch yesterday and will be included in the next release 😄

**Comment by SageDearborn** [comment]
Can we please update the documentation page located here: https://snipe-it.readme.io/docs/importing to reflect that the field name should be "Serial Number" not "Serial". Additionally, can the sample CSV be updated from "Serial number" to "Serial Number"?

This discrepancy caused all my assets to import without serial numbers and I would be grateful for the fix to the documentation.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>

**Comment by joemdiente** [comment]
This is still an issue. Documentation shows "Serial" and not "Serial Number". Thanks

**Comment by snipe** [comment]
It shouldn’t matter as long as it’s mapped correctly on the import.
