### ISSUE TITLE
Asset Tag in Maintenance

### ISSUE THREAD

**Issue by Voyager-2** [snipe/snipe-it#5151]
#### Expected Behavior (or desired behavior if a feature request)
Ability to view an item's Asset Tag in maintenance records.

-----

#### Actual Behavior
Inside the Maintenance page column select dropdown, only "Asset Name" is available

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode. (I do not believe this is a bug, just a feature request. I can enable debug if it is required for this, though.)
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh

- Version of Snipe-IT you're running
 4.1.11

- Version of PHP you're running 
7.1.13

- Version of MySQL/MariaDB you're running 
5.5.56

- What OS and web server you're running Snipe-IT on 
CentOS7

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Debug is not currently enabled

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error 
Asset Mainenance page, no error

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
I can confirm that the feature I am requesting is not available on the demo

- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No manual editing of database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

_______________________________________
First off I just want to thank you guys for developing such an amazing product. I work for a school district and as such our budget is extremely tight - SnipeIT is a blessing for us.

Basically what I'm looking for is the ability for Asset Tags to be displayed in the Maintenance page. In our deployment, we do not use the "Asset Name" field unless a device is somehow special (The asset tag "LT0001" is also the name of the device so the "Asset Name" field is largely redundant). To me, this would seem to be the desired function of a Maintenance report anyway because Asset Tags are unique, whereas Asset Names are not.

This is what the asset maintenance page looks like if your assets do not have an "Asset Name" I have confirmed in the demo that this is the case there as well.
![image](https://user-images.githubusercontent.com/37075798/36980943-673543c4-2051-11e8-9ace-82694f862ef8.png)

This is from the edit view of a maintenance record. The Asset Tag is correctly shown here as part of the name, if this could carry over to the overall Maintenance page, that would be wonderful.
![image](https://user-images.githubusercontent.com/37075798/36981145-f8651efa-2051-11e8-8927-c177b94cd88d.png)

If this is somehow already possible and I'm just too dense to figure it out, please let me know. Thanks again for the work you all do.

**Comment by sysnoo** [comment]
I have the latest release. Is the issue fixed?
I Just noticed this.
Asset name is empty and there is no column for asset tag.

However, the asset name seems present in the raw results returned by .../api/v1/maintenances?sort=id&order=asc&offset=0&limit=500
it's just not visible in the displayed report

**Comment by Voyager-2** [comment]
It worked on my installation, the option is not checked by default though, you have to click on the columns to display and select asset tag

**Comment by sysnoo** [comment]
Me I cannot see it.
![image](https://user-images.githubusercontent.com/13991151/37991717-df60e55a-31d7-11e8-9df7-00e69574bde0.png)

**Comment by sysnoo** [comment]
By Fixed, Does that mean. 
Fixed in the current release or in the one to come?
Thanks

**Comment by sysnoo** [comment]
Oupps,
I noticed the issue is also there in SnipeIT live demo.

![image](https://user-images.githubusercontent.com/13991151/38100007-13ffc18c-334a-11e8-90df-022b37341490.png)

**Comment by fofwisdom** [comment]
I was updated to v4.2.0, today. And checked #5115 - https://github.com/4nn0/snipe-it/commit/1f528ff113d007c7009705cbfc8f3a76474f794b. But Asset Tag still not showing.

Review please.

**Comment by sysnoo** [comment]
Asset Name missing in Maintenance Report even in online demo.
![image](https://user-images.githubusercontent.com/13991151/39590067-d0790492-4ecd-11e8-9cb0-ae1671d32c0b.png)

**Comment by snipe** [comment]
@sysnoo The asset maintenances report has the same information in it as the Assets > Asset Maintenances screen. It's redundant and will likely be deprecated.

**Comment by sysnoo** [comment]
Thanks. I can  see it know. I think, issue can be closed.

**Comment by morrow72** [comment]
hi there. even if this post is from last year and based on ver. 4.1.1, i've got the same problem, no asset names are displayed in asset maintenance report.
information is shown in assets - asset maintenance with asset name and asset tag
in maintenance report, asset name is empty and i can't select asset tag in the column drop down.
Snipe-IT v4.6.3 - build 3866 (master)
