### ISSUE TITLE
Users can't login after 4.5 to 4.6 update

### ISSUE THREAD

**Issue by romannazarenko** [snipe/snipe-it#5893]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Users can't login after 4.5 to 4.6 update. LDAP login worked fine before update, Test LDAP Login
give me "User authenticated against LDAP successfully!"
After user login fails, error in logs:

[2018-07-19 15:37:22] production.ERROR: There was an error authenticating the LDAP user: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'active' in 'where clause' (SQL: select * from `users` where `username` = ********* and `deleted_at` is null and `ldap_import` = 1 and `active` = 1 and `users`.`deleted_at` is null limit 1)

**Comment by pcsmarts502** [comment]
I had the same problem.  Definitely a Bug.  I used the password reset feature  which allowed me to reset my password to the same one.  That worked for me.

**Comment by egroeneveld** [comment]
We're seeing the same problem here as well. We're also not able to create new users anymore (whoops! something went wrong here error).

LDAP users get 'password incorrect', while the Test LDAP works fine. Fortunatly I had a second account in our installation, otherwise I couldn't access anymore.

**Comment by pcsmarts502** [comment]
I just updated to 4.6.1 and the issue with the login still there.  I have currently instructed my users to use the forgot my password to reset.  That appears to work fine.  I don't understand what's happening though.  Some of my users with their password stored in their browsers seem to have no issues.

**Comment by snipe** [comment]
@pcsmarts502 check their activated status in the users section

**Comment by clcit** [comment]
I think there is another line that needs to be updated in LoginController.php.  I posted this as a comment on the a0c0b7b commit.

After pulling down the new version of LoginController.php with the php upgrade.php command, our users still could not login with LDAP. In looking at the file, it looks like 'active' needs to be changed to 'activated' at line 100 also. After I made this edit, users can login.

Sorry if I should have posted here.

**Comment by pcsmarts502** [comment]
They appear to have a green check

**Comment by snipe** [comment]
@pcsmarts502 I just pushed out another small fix

**Comment by n-v-o** [comment]
@snipe ha, I was just writing up a bug report on this!

**Comment by pcsmarts502** [comment]
That seems to have fixed it.  THANKS

**Comment by snipe** [comment]
@n-v-o 💥 ahead of you :)

@pcsmarts502 great, sorry for the morning PITA

**Comment by egroeneveld** [comment]
Thanks for the quick fix! Confirmed working here with 4.6.2.

**Comment by snipe** [comment]
@shan224 Dockerhub should build on pushes to master/develop, but it also builds on tags (which means releases). I just pushed the v4.6.3 tag, so give it a moment until it's done building and then you should be able to pull 4.6.3.

**Comment by pslobo** [comment]
I've just updated to 4.6.3 and I'm still seeing this exact same issue. Granted I'm the admin ser and can't change myself to active (even though this wasn't an issue in 4.4.x)

Any ideas?

**Comment by merentitis** [comment]
I also experience the same problem, EACH time I LDAP sync, all users get deactivated. I run this mysql query every time as a temp fix:
```
use snipeit;
UPDATE users set activated = '1' WHERE activated = 0;
```

**Comment by stbc** [comment]
Same over here, is that intended behaviour or a bug?

**Comment by merentitis** [comment]
The issue is still present in the latest version

**Comment by stbc** [comment]
Can we reopen this issue then? Is that only me and @merentitis having this issue?

**Comment by snipe** [comment]
I believe this has already been fixed on the develop branch and will be in v5, but I'm reopening so I can confirm that.

**Comment by rufy89** [comment]
> Can we reopen this issue then? Is that only me and @merentitis having this issue?

I'm havig the issue as well using v4.6.13.

**Comment by rufy89** [comment]
> > Can we reopen this issue then? Is that only me and @merentitis having this issue?
> 
> I'm havig the issue as well using v4.6.13.

This [fix for #5054](https://github.com/snipe/snipe-it/commit/5b8cbe29e182c691fa71911bdee403610bda2978) solved it.

**Comment by merentitis** [comment]
@rufy89 Indeed, that solved it, thanks for sharing
@stbc
