### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'activated' cannot be null 

### ISSUE THREAD

**Issue by andreasoc** [snipe/snipe-it#5927]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When create a new user, and don't check the box "Active This user can login" receive the error in subject

**To Reproduce**

**Expected behavior**
Snipe-it  should tell me that the field is mandatory or is not mandatory.. give me the possibility to create the user anyway

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.0
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version

**Comment by dmeltzer** [comment]
This is fixed in https://github.com/snipe/snipe-it/commit/d309f67df011e1c98d6e3f3dcd8aa13d97bab357, which is part of 4.6.2.  Try upgrading when convenient.

**Comment by andreasoc** [comment]
thanks

**Comment by snipe** [comment]
@dmeltzer Actually, that one wasn't fixed - that commit was for the update method, not the create method. It's fixed on develop now tho.
