### ISSUE TITLE
Unable to Load Assets Page

### ISSUE THREAD

**Issue by Damancor** [snipe/snipe-it#6522]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
 
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
Yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
Yes, Couldn't find the a solution. 
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh installation.
- Version of Snipe-IT you're running
v4.6.6 build 3926 (g1a10aa0dd)
- Version of PHP you're running
7.3.0
- Version of MySQL/MariaDB you're running
MariaDB 10.0.37
- What OS and web server you're running Snipe-IT on
Windows Server 2012 Rd Datacenter
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Failed to load resource: the server responded with a status of 500 (Internal Server Error)    hardware:1
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
When I try and open the Asset section. I get a internal server error 500/ (2/2) ErrorException
compact(): Undefined variable: operator (View: C:\inetpub\wwwroot\snipe-it\resources\views\hardware\index.blade.php) / (1/2) ErrorException
compact(): Undefined variable: operator
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)    hardware:1
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No I do not get the error in the demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
Installation and preflight completed. Only issue is the assets page.
- Indicate whether or not you've manually edited any data directly in the database
No I haven't edited the database manually.
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Damancor** [comment]
Here is the error log from debugging.


(2/2) ErrorExceptioncompact(): Undefined variable: operator (View: C:\inetpub\wwwroot\snipe-it\resources\views\hardware\index.blade.php)
--
in Builder.php line 1229
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php line 44
at PhpEngine->evaluatePath('C:\\inetpub\\wwwroot\\snipe-it\\storage\\framework\\views/1af8e7af68c3eb76505b1fdb721ef685b8a9373a.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' => object(Setting)))in CompilerEngine.php line 59
at CompilerEngine->get('C:\\inetpub\\wwwroot\\snipe-it\\resources\\views/hardware/index.blade.php', array('__env' => object(Factory), 'app' =>object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' => object(Setting)))in View.php line 137
at View->getContents()in View.php line 120
at View->renderContents()in View.php line 85
at View->render()in Response.php line 38
at Response->setContent(object(View))in Response.php line 206
at Response->__construct(object(View))in Router.php line 615
at Router->prepareResponse(object(Request), object(View))in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Comment by Damancor** [comment]
(1/2) ErrorExceptioncompact(): Undefined variable: operator
--
in Builder.php line 1229
at HandleExceptions->handleError(8, 'compact(): Undefined variable: operator', 'C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php', 1229, array('query' => object(Builder), 'boolean' => 'and', 'not' => false, 'type' => 'Exists'))
at compact('type', 'operator', 'query', 'boolean')in Builder.php line 1229
at Builder->addWhereExistsQuery(object(Builder), 'and', false)in Builder.php line 1254
at Builder->__call('addWhereExistsQuery', array(object(Builder), 'and', false))in QueriesRelationships.php line 242
at Builder->addHasWhere(object(Builder), object(HasMany), '>=', 1, 'and')in QueriesRelationships.php line 52
at Builder->has(object(HasMany), '>=', 1, 'and', null)in QueriesRelationships.php line 132
at Builder->whereHas('models')in AssetPresenter.php line 258
at AssetPresenter::App\Presenters\{closure}(object(Builder))in Builder.php line 934
at Builder->callScope(object(Closure))in QueriesRelationships.php line 48
at Builder->has(object(BelongsToMany), '>=', 1, 'and', object(Closure))in QueriesRelationships.php line 132
at Builder->whereHas('fieldset', object(Closure))in Model.php line 1374
at Model->__call('whereHas', array('fieldset', object(Closure)))in Model.php line 1386
at Model::__callStatic('whereHas', array('fieldset', object(Closure)))in AssetPresenter.php line 259
at AssetPresenter::dataTableLayout()in 1af8e7af68c3eb76505b1fdb721ef685b8a9373a.php line 89
at include('C:\\inetpub\\wwwroot\\snipe-it\\storage\\framework\\views\\1af8e7af68c3eb76505b1fdb721ef685b8a9373a.php')in PhpEngine.php line 42
at PhpEngine->evaluatePath('C:\\inetpub\\wwwroot\\snipe-it\\storage\\framework\\views/1af8e7af68c3eb76505b1fdb721ef685b8a9373a.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' => object(Setting)))in CompilerEngine.php line 59
at CompilerEngine->get('C:\\inetpub\\wwwroot\\snipe-it\\resources\\views/hardware/index.blade.php', array('__env' => object(Factory), 'app' =>object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' => object(Setting)))in View.php line 137
at View->getContents()in View.php line 120
at View->renderContents()in View.php line 85
at View->render()in Response.php line 38
at Response->setContent(object(View))in Response.php line 206
at Response->__construct(object(View))in Router.php line 615
at Router->prepareResponse(object(Request), object(View))in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Comment by aoodpr** [comment]
Dear, I have same issue, how do you solve it ?

**Comment by Damancor** [comment]
Hi @aoodpr ,

Which version of PHP are you using? I had to downgrade from 7.3 to 7.0.33 in order for this to work.

**Comment by astrava** [comment]
I have the same issue new install on CentOS 7.6 & PHP7.3 .

**Comment by astrava** [comment]
tail  storage/logs/laravel.log 
#75 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#78 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#81 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#82 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#83 /var/www/snipe-it/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#84 {main}

**Comment by Damancor** [comment]
Hi @astrava ,

i would try downgrading your PHP version to 7.0.33. Once I did this the assets page loaded correctly.

**Comment by aoodpr** [comment]
Downgrade from php 7.3 to php-7.2.13, it seems work fine now, except when user made asset request.

**Comment by BATHIVINOD2** [comment]
Hi @Damancor @aoodpr  @snipe 
I too facing the same problem but Downgrading PHP version is not the solution to work, bcoz further versions won't work with older PHP versions, please suggest without Downgrading.

**Comment by snipe** [comment]
@BATHIVINOD2 this issue is resolved in the upcoming Snipe-IT v5.

**Comment by BATHIVINOD2** [comment]
@snipe 
Thanks for the update

**Comment by gregwho** [comment]
Version 4.6.7 is supposed to work with php 7.3 but I'm still getting this error from that version of snipeit.

**Comment by BATHIVINOD2** [comment]
please collaborate the issue

**Comment by ThangTranDuc** [comment]
> i would try downgrading your PHP version to 7.0.33. Once I did this the assets page loaded correctly.
Can you show me details how to downgrading PHP version from 7.3.3 to 7.0.33?

**Comment by mongcam047** [comment]
Hi everyone, 
Thank for your supported
This issue resolved when i downgrade version php from 7.3.3 to 7.1.28.
