### ISSUE TITLE
Bug - Expiring Licenses Report - Shows licenses greater than 60 days out

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#909]
![image](https://cloud.githubusercontent.com/assets/10247644/8650446/e3c1cab2-2940-11e5-9369-5a85730616ed.png)

**Comment by snipe** [comment]
Should be fixed in 2.0 branch

**Comment by kobie-chasehansen** [comment]
Been playing in the 2.0 branch and noticed today this issue still exists...

**Comment by snipe** [comment]
Can you give me some sample data (obfuscated, if necessary). I've tested this and haven't been able to reproduce it locally

**Comment by snipe** [comment]
@kobie-chasehansen check the 2.0 branch again, I just pushed up a change that should hopefully fix this.

**Comment by kobie-chasehansen** [comment]
verified fixed

**Comment by snipe** [comment]
![yxdzy](https://cloud.githubusercontent.com/assets/197404/8938942/724be28c-3516-11e5-84da-42ac5cbe69d9.gif)
